
/*
 * Copyright (c) 2012, Freescale Semiconductor, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without modification,
 * are permitted provided that the following conditions are met:
 *
 * o Redistributions of source code must retain the above copyright notice, this list
 *   of conditions and the following disclaimer.
 *
 * o Redistributions in binary form must reproduce the above copyright notice, this
 *   list of conditions and the following disclaimer in the documentation and/or
 *   other materials provided with the distribution.
 *
 * o Neither the name of Freescale Semiconductor, Inc. nor the names of its
 *   contributors may be used to endorse or promote products derived from this
 *   software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
 * ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

#ifndef _IOMUX_DEFINES_H_
#define _IOMUX_DEFINES_H_

/* IOMUXC - Register offsets */
#define SW_MUX_CTL_PAD_PAD_0_OFFSET 0x00000000
#define IOMUXC_SW_MUX_CTL_PAD_PAD_1_OFFSET 0x00000004
#define IOMUXC_SW_MUX_CTL_PAD_PAD_2_OFFSET 0x00000008
#define IOMUXC_SW_MUX_CTL_PAD_PAD_3_OFFSET 0x0000000C
#define IOMUXC_SW_MUX_CTL_PAD_PAD_4_OFFSET 0x00000010
#define IOMUXC_SW_MUX_CTL_PAD_PAD_5_OFFSET 0x00000014
#define IOMUXC_SW_MUX_CTL_PAD_PAD_6_OFFSET 0x00000018
#define IOMUXC_SW_MUX_CTL_PAD_PAD_7_OFFSET 0x0000001C
#define IOMUXC_SW_MUX_CTL_PAD_PAD_8_OFFSET 0x00000020
#define IOMUXC_SW_MUX_CTL_PAD_PAD_9_OFFSET 0x00000024
#define IOMUXC_SW_MUX_CTL_PAD_PAD_10_OFFSET 0x00000028
#define IOMUXC_SW_MUX_CTL_PAD_PAD_11_OFFSET 0x0000002C
#define IOMUXC_SW_MUX_CTL_PAD_PAD_12_OFFSET 0x00000030
#define IOMUXC_SW_MUX_CTL_PAD_PAD_13_OFFSET 0x00000034
#define IOMUXC_SW_MUX_CTL_PAD_PAD_14_OFFSET 0x00000038
#define IOMUXC_SW_MUX_CTL_PAD_PAD_15_OFFSET 0x0000003C
#define IOMUXC_SW_MUX_CTL_PAD_PAD_16_OFFSET 0x00000040
#define IOMUXC_SW_MUX_CTL_PAD_PAD_17_OFFSET 0x00000044
#define IOMUXC_SW_MUX_CTL_PAD_PAD_18_OFFSET 0x00000048
#define IOMUXC_SW_MUX_CTL_PAD_PAD_19_OFFSET 0x0000004C
#define IOMUXC_SW_MUX_CTL_PAD_PAD_20_OFFSET 0x00000050
#define IOMUXC_SW_MUX_CTL_PAD_PAD_21_OFFSET 0x00000054
#define IOMUXC_SW_MUX_CTL_PAD_PAD_22_OFFSET 0x00000058
#define IOMUXC_SW_MUX_CTL_PAD_PAD_23_OFFSET 0x0000005C
#define IOMUXC_SW_MUX_CTL_PAD_PAD_24_OFFSET 0x00000060
#define IOMUXC_SW_MUX_CTL_PAD_PAD_25_OFFSET 0x00000064
#define IOMUXC_SW_MUX_CTL_PAD_PAD_26_OFFSET 0x00000068
#define IOMUXC_SW_MUX_CTL_PAD_PAD_27_OFFSET 0x0000006C
#define IOMUXC_SW_MUX_CTL_PAD_PAD_28_OFFSET 0x00000070
#define IOMUXC_SW_MUX_CTL_PAD_PAD_29_OFFSET 0x00000074
#define IOMUXC_SW_MUX_CTL_PAD_PAD_30_OFFSET 0x00000078
#define IOMUXC_SW_MUX_CTL_PAD_PAD_31_OFFSET 0x0000007C
#define IOMUXC_SW_MUX_CTL_PAD_PAD_32_OFFSET 0x00000080
#define IOMUXC_SW_MUX_CTL_PAD_PAD_33_OFFSET 0x00000084
#define IOMUXC_SW_MUX_CTL_PAD_PAD_34_OFFSET 0x00000088
#define IOMUXC_SW_MUX_CTL_PAD_PAD_35_OFFSET 0x0000008C
#define IOMUXC_SW_MUX_CTL_PAD_PAD_36_OFFSET 0x00000090
#define IOMUXC_SW_MUX_CTL_PAD_PAD_37_OFFSET 0x00000094
#define IOMUXC_SW_MUX_CTL_PAD_PAD_38_OFFSET 0x00000098
#define IOMUXC_SW_MUX_CTL_PAD_PAD_39_OFFSET 0x0000009C
#define IOMUXC_SW_MUX_CTL_PAD_PAD_40_OFFSET 0x000000A0
#define IOMUXC_SW_MUX_CTL_PAD_PAD_41_OFFSET 0x000000A4
#define IOMUXC_SW_MUX_CTL_PAD_PAD_42_OFFSET 0x000000A8
#define IOMUXC_SW_MUX_CTL_PAD_PAD_43_OFFSET 0x000000AC
#define IOMUXC_SW_MUX_CTL_PAD_PAD_44_OFFSET 0x000000B0
#define IOMUXC_SW_MUX_CTL_PAD_PAD_45_OFFSET 0x000000B4
#define IOMUXC_SW_MUX_CTL_PAD_PAD_46_OFFSET 0x000000B8
#define IOMUXC_SW_MUX_CTL_PAD_PAD_47_OFFSET 0x000000BC
#define IOMUXC_SW_MUX_CTL_PAD_PAD_48_OFFSET 0x000000C0
#define IOMUXC_SW_MUX_CTL_PAD_PAD_49_OFFSET 0x000000C4
#define IOMUXC_SW_MUX_CTL_PAD_PAD_50_OFFSET 0x000000C8
#define IOMUXC_SW_MUX_CTL_PAD_PAD_51_OFFSET 0x000000CC
#define IOMUXC_SW_MUX_CTL_PAD_PAD_52_OFFSET 0x000000D0
#define IOMUXC_SW_MUX_CTL_PAD_PAD_53_OFFSET 0x000000D4
#define IOMUXC_SW_MUX_CTL_PAD_PAD_54_OFFSET 0x000000D8
#define IOMUXC_SW_MUX_CTL_PAD_PAD_55_OFFSET 0x000000DC
#define IOMUXC_SW_MUX_CTL_PAD_PAD_56_OFFSET 0x000000E0
#define IOMUXC_SW_MUX_CTL_PAD_PAD_57_OFFSET 0x000000E4
#define IOMUXC_SW_MUX_CTL_PAD_PAD_58_OFFSET 0x000000E8
#define IOMUXC_SW_MUX_CTL_PAD_PAD_59_OFFSET 0x000000EC
#define IOMUXC_SW_MUX_CTL_PAD_PAD_60_OFFSET 0x000000F0
#define IOMUXC_SW_MUX_CTL_PAD_PAD_61_OFFSET 0x000000F4
#define IOMUXC_SW_MUX_CTL_PAD_PAD_62_OFFSET 0x000000F8
#define IOMUXC_SW_MUX_CTL_PAD_PAD_63_OFFSET 0x000000FC
#define IOMUXC_SW_MUX_CTL_PAD_PAD_64_OFFSET 0x00000100
#define IOMUXC_SW_MUX_CTL_PAD_PAD_65_OFFSET 0x00000104
#define IOMUXC_SW_MUX_CTL_PAD_PAD_66_OFFSET 0x00000108
#define IOMUXC_SW_MUX_CTL_PAD_PAD_67_OFFSET 0x0000010C
#define IOMUXC_SW_MUX_CTL_PAD_PAD_68_OFFSET 0x00000110
#define IOMUXC_SW_MUX_CTL_PAD_PAD_69_OFFSET 0x00000114
#define IOMUXC_SW_MUX_CTL_PAD_PAD_70_OFFSET 0x00000118
#define IOMUXC_SW_MUX_CTL_PAD_PAD_71_OFFSET 0x0000011C
#define IOMUXC_SW_MUX_CTL_PAD_PAD_72_OFFSET 0x00000120
#define IOMUXC_SW_MUX_CTL_PAD_PAD_73_OFFSET 0x00000124
#define IOMUXC_SW_MUX_CTL_PAD_PAD_74_OFFSET 0x00000128
#define IOMUXC_SW_MUX_CTL_PAD_PAD_75_OFFSET 0x0000012C
#define IOMUXC_SW_MUX_CTL_PAD_PAD_76_OFFSET 0x00000130
#define IOMUXC_SW_MUX_CTL_PAD_PAD_77_OFFSET 0x00000134
#define IOMUXC_SW_MUX_CTL_PAD_PAD_78_OFFSET 0x00000138
#define IOMUXC_SW_MUX_CTL_PAD_PAD_79_OFFSET 0x0000013C
#define IOMUXC_SW_MUX_CTL_PAD_PAD_80_OFFSET 0x00000140
#define IOMUXC_SW_MUX_CTL_PAD_PAD_81_OFFSET 0x00000144
#define IOMUXC_SW_MUX_CTL_PAD_PAD_82_OFFSET 0x00000148
#define IOMUXC_SW_MUX_CTL_PAD_PAD_83_OFFSET 0x0000014C
#define IOMUXC_SW_MUX_CTL_PAD_PAD_84_OFFSET 0x00000150
#define IOMUXC_SW_MUX_CTL_PAD_PAD_85_OFFSET 0x00000154
#define IOMUXC_SW_MUX_CTL_PAD_PAD_86_OFFSET 0x00000158
#define IOMUXC_SW_MUX_CTL_PAD_PAD_87_OFFSET 0x0000015C
#define IOMUXC_SW_MUX_CTL_PAD_PAD_88_OFFSET 0x00000160
#define IOMUXC_SW_MUX_CTL_PAD_PAD_89_OFFSET 0x00000164
#define IOMUXC_SW_MUX_CTL_PAD_PAD_90_OFFSET 0x00000168
#define IOMUXC_SW_MUX_CTL_PAD_PAD_91_OFFSET 0x0000016C
#define IOMUXC_SW_MUX_CTL_PAD_PAD_92_OFFSET 0x00000170
#define IOMUXC_SW_MUX_CTL_PAD_PAD_93_OFFSET 0x00000174
#define IOMUXC_SW_MUX_CTL_PAD_PAD_94_OFFSET 0x00000178
#define IOMUXC_SW_MUX_CTL_PAD_PAD_95_OFFSET 0x0000017C
#define IOMUXC_SW_MUX_CTL_PAD_PAD_96_OFFSET 0x00000180
#define IOMUXC_SW_MUX_CTL_PAD_PAD_97_OFFSET 0x00000184
#define IOMUXC_SW_MUX_CTL_PAD_PAD_98_OFFSET 0x00000188
#define IOMUXC_SW_MUX_CTL_PAD_PAD_99_OFFSET 0x0000018C
#define IOMUXC_SW_MUX_CTL_PAD_PAD_100_OFFSET 0x00000190
#define IOMUXC_SW_MUX_CTL_PAD_PAD_101_OFFSET 0x00000194
#define IOMUXC_SW_MUX_CTL_PAD_PAD_102_OFFSET 0x00000198
#define IOMUXC_SW_MUX_CTL_PAD_PAD_103_OFFSET 0x0000019C
#define IOMUXC_SW_MUX_CTL_PAD_PAD_104_OFFSET 0x000001A0
#define IOMUXC_SW_MUX_CTL_PAD_PAD_105_OFFSET 0x000001A4
#define IOMUXC_SW_MUX_CTL_PAD_PAD_106_OFFSET 0x000001A8
#define IOMUXC_SW_MUX_CTL_PAD_PAD_107_OFFSET 0x000001AC
#define IOMUXC_SW_MUX_CTL_PAD_PAD_108_OFFSET 0x000001B0
#define IOMUXC_SW_MUX_CTL_PAD_PAD_109_OFFSET 0x000001B4
#define IOMUXC_SW_MUX_CTL_PAD_PAD_110_OFFSET 0x000001B8
#define IOMUXC_SW_MUX_CTL_PAD_PAD_111_OFFSET 0x000001BC
#define IOMUXC_SW_MUX_CTL_PAD_PAD_112_OFFSET 0x000001C0
#define IOMUXC_SW_MUX_CTL_PAD_PAD_113_OFFSET 0x000001C4
#define IOMUXC_SW_MUX_CTL_PAD_PAD_114_OFFSET 0x000001C8
#define IOMUXC_SW_MUX_CTL_PAD_PAD_115_OFFSET 0x000001CC
#define IOMUXC_SW_MUX_CTL_PAD_PAD_116_OFFSET 0x000001D0
#define IOMUXC_SW_MUX_CTL_PAD_PAD_117_OFFSET 0x000001D4
#define IOMUXC_SW_MUX_CTL_PAD_PAD_118_OFFSET 0x000001D8
#define IOMUXC_SW_MUX_CTL_PAD_PAD_119_OFFSET 0x000001DC
#define IOMUXC_SW_MUX_CTL_PAD_PAD_120_OFFSET 0x000001E0
#define IOMUXC_SW_MUX_CTL_PAD_PAD_121_OFFSET 0x000001E4
#define IOMUXC_SW_MUX_CTL_PAD_PAD_122_OFFSET 0x000001E8
#define IOMUXC_SW_MUX_CTL_PAD_PAD_123_OFFSET 0x000001EC
#define IOMUXC_SW_MUX_CTL_PAD_PAD_124_OFFSET 0x000001F0
#define IOMUXC_SW_MUX_CTL_PAD_PAD_125_OFFSET 0x000001F4
#define IOMUXC_SW_MUX_CTL_PAD_PAD_126_OFFSET 0x000001F8
#define IOMUXC_SW_MUX_CTL_PAD_PAD_127_OFFSET 0x000001FC
#define IOMUXC_SW_MUX_CTL_PAD_PAD_128_OFFSET 0x00000200
#define IOMUXC_SW_MUX_CTL_PAD_PAD_129_OFFSET 0x00000204
#define IOMUXC_SW_MUX_CTL_PAD_PAD_130_OFFSET 0x00000208
#define IOMUXC_SW_MUX_CTL_PAD_PAD_131_OFFSET 0x0000020C
#define IOMUXC_SW_MUX_CTL_PAD_PAD_132_OFFSET 0x00000210
#define IOMUXC_SW_MUX_CTL_PAD_PAD_133_OFFSET 0x00000214
#define IOMUXC_SW_MUX_CTL_PAD_PAD_134_OFFSET 0x00000218
#define IOMUXC_SW_MUX_CTL_PAD_DDR_RESETB_OFFSET 0x0000021C
#define IOMUXC_SW_MUX_CTL_PAD_DDR_A_15_OFFSET 0x00000220
#define IOMUXC_SW_MUX_CTL_PAD_DDR_A_14_OFFSET 0x00000224
#define IOMUXC_SW_MUX_CTL_PAD_DDR_A_13_OFFSET 0x00000228
#define IOMUXC_SW_MUX_CTL_PAD_DDR_A_12_OFFSET 0x0000022C
#define IOMUXC_SW_MUX_CTL_PAD_DDR_A_11_OFFSET 0x00000230
#define IOMUXC_SW_MUX_CTL_PAD_DDR_A_10_OFFSET 0x00000234
#define IOMUXC_SW_MUX_CTL_PAD_DDR_A_9_OFFSET 0x00000238
#define IOMUXC_SW_MUX_CTL_PAD_DDR_A_8_OFFSET 0x0000023C
#define IOMUXC_SW_MUX_CTL_PAD_DDR_A_7_OFFSET 0x00000240
#define IOMUXC_SW_MUX_CTL_PAD_DDR_A_6_OFFSET 0x00000244
#define IOMUXC_SW_MUX_CTL_PAD_DDR_A_5_OFFSET 0x00000248
#define IOMUXC_SW_MUX_CTL_PAD_DDR_A_4_OFFSET 0x0000024C
#define IOMUXC_SW_MUX_CTL_PAD_DDR_A_3_OFFSET 0x00000250
#define IOMUXC_SW_MUX_CTL_PAD_DDR_A_2_OFFSET 0x00000254
#define IOMUXC_SW_MUX_CTL_PAD_DDR_A_1_OFFSET 0x00000258
#define IOMUXC_SW_MUX_CTL_PAD_DDR_A_0_OFFSET 0x0000025C
#define IOMUXC_SW_MUX_CTL_PAD_DDR_BA_2_OFFSET 0x00000260
#define IOMUXC_SW_MUX_CTL_PAD_DDR_BA_1_OFFSET 0x00000264
#define IOMUXC_SW_MUX_CTL_PAD_DDR_BA_0_OFFSET 0x00000268
#define IOMUXC_SW_MUX_CTL_PAD_DDR_CAS_B_OFFSET 0x0000026C
#define IOMUXC_SW_MUX_CTL_PAD_DDR_CKE_0_OFFSET 0x00000270
#define IOMUXC_SW_MUX_CTL_PAD_DDR_CLK_0_OFFSET 0x00000274
#define IOMUXC_SW_MUX_CTL_PAD_DDR_CS_B_0_OFFSET 0x00000278
#define IOMUXC_SW_MUX_CTL_PAD_DDR_D_15_OFFSET 0x0000027C
#define IOMUXC_SW_MUX_CTL_PAD_DDR_D_14_OFFSET 0x00000280
#define IOMUXC_SW_MUX_CTL_PAD_DDR_D_13_OFFSET 0x00000284
#define IOMUXC_SW_MUX_CTL_PAD_DDR_D_12_OFFSET 0x00000288
#define IOMUXC_SW_MUX_CTL_PAD_DDR_D_11_OFFSET 0x0000028C
#define IOMUXC_SW_MUX_CTL_PAD_DDR_D_10_OFFSET 0x00000290
#define IOMUXC_SW_MUX_CTL_PAD_DDR_D_9_OFFSET 0x00000294
#define IOMUXC_SW_MUX_CTL_PAD_DDR_D_8_OFFSET 0x00000298
#define IOMUXC_SW_MUX_CTL_PAD_DDR_D_7_OFFSET 0x0000029C
#define IOMUXC_SW_MUX_CTL_PAD_DDR_D_6_OFFSET 0x000002A0
#define IOMUXC_SW_MUX_CTL_PAD_DDR_D_5_OFFSET 0x000002A4
#define IOMUXC_SW_MUX_CTL_PAD_DDR_D_4_OFFSET 0x000002A8
#define IOMUXC_SW_MUX_CTL_PAD_DDR_D_3_OFFSET 0x000002AC
#define IOMUXC_SW_MUX_CTL_PAD_DDR_D_2_OFFSET 0x000002B0
#define IOMUXC_SW_MUX_CTL_PAD_DDR_D_1_OFFSET 0x000002B4
#define IOMUXC_SW_MUX_CTL_PAD_DDR_D_0_OFFSET 0x000002B8
#define IOMUXC_SW_MUX_CTL_PAD_DDR_DQM_1_OFFSET 0x000002BC
#define IOMUXC_SW_MUX_CTL_PAD_DDR_DQM_0_OFFSET 0x000002C0
#define IOMUXC_SW_MUX_CTL_PAD_DDR_DQS_1_OFFSET 0x000002C4
#define IOMUXC_SW_MUX_CTL_PAD_DDR_DQS_0_OFFSET 0x000002C8
#define IOMUXC_SW_MUX_CTL_PAD_DDR_RAS_B_OFFSET 0x000002CC
#define IOMUXC_SW_MUX_CTL_PAD_DDR_WE_B_OFFSET 0x000002D0
#define IOMUXC_SW_MUX_CTL_PAD_DDR_ODT_0_OFFSET 0x000002D4
#define IOMUXC_SW_MUX_CTL_PAD_DDR_ODT_1_OFFSET 0x000002D8
#define IOMUXC_SW_MUX_CTL_PAD_DUMMY_DDRBYTE1_OFFSET 0x000002DC
#define IOMUXC_SW_MUX_CTL_PAD_DUMMY_DDRBYTE2_OFFSET 0x000002E0
#define IOMUXC_SW_MUX_CTL_PAD_DUMMY_SDHCE1_OFFSET 0x000002E4
#define IOMUXC_SW_MUX_CTL_PAD_DUMMY_SDHC2_OFFSET 0x000002E8
#define IOMUXC_CCM_AUD_EXT_CLK_SELECT_INPUT_OFFSET 0x000002EC
#define IOMUXC_CCM_ENET_EXT_CLK_SELECT_INPUT_OFFSET 0x000002F0
#define IOMUXC_CCM_ENET_TS_CLK_SELECT_INPUT_OFFSET 0x000002F4
#define IOMUXC_DSPI1_IPP_IND_SCK_SELECT_INPUT_OFFSET 0x000002F8
#define IOMUXC_DSPI1_IPP_IND_SIN_SELECT_INPUT_OFFSET 0x000002FC
#define IOMUXC_DSPI1_IPP_IND_SS_B_SELECT_INPUT_OFFSET 0x00000300
#define IOMUXC_ENET_SWIAHB_IPP_IND_MAC0_TIMER_0_SELECT_INPUT_OFFSET 0x00000304
#define IOMUXC_ENET_SWIAHB_IPP_IND_MAC0_TIMER_1_SELECT_INPUT_OFFSET 0x00000308
#define IOMUXC_ESAI_IPP_IND_FST_SELECT_INPUT_OFFSET 0x0000030C
#define IOMUXC_ESAI_IPP_IND_SCKT_SELECT_INPUT_OFFSET 0x00000310
#define IOMUXC_ESAI_IPP_IND_SDO0_SELECT_INPUT_OFFSET 0x00000314
#define IOMUXC_ESAI_IPP_IND_SDO1_SELECT_INPUT_OFFSET 0x00000318
#define IOMUXC_ESAI_IPP_IND_SDO2_SDI3_SELECT_INPUT_OFFSET 0x0000031C
#define IOMUXC_ESAI_IPP_IND_SDO3_SDI2_SELECT_INPUT_OFFSET 0x00000320
#define IOMUXC_ESAI_IPP_IND_SDO4_SDI1_SELECT_INPUT_OFFSET 0x00000324
#define IOMUXC_ESAI_IPP_IND_SDO5_SDI0_SELECT_INPUT_OFFSET 0x00000328
#define IOMUXC_FLEXTIMER1_IPP_IND_FTM_CH_0_SELECT_INPUT_OFFSET 0x0000032C
#define IOMUXC_FLEXTIMER1_IPP_IND_FTM_CH_1_SELECT_INPUT_OFFSET 0x00000330
#define IOMUXC_FLEXTIMER1_IPP_IND_FTM_PHA_SELECT_INPUT_OFFSET 0x00000334
#define IOMUXC_FLEXTIMER1_IPP_IND_FTM_PHB_SELECT_INPUT_OFFSET 0x00000338
#define IOMUXC_I2C0_IPP_SCL_IND_SELECT_INPUT_OFFSET 0x0000033C
#define IOMUXC_I2C0_IPP_SDA_IND_SELECT_INPUT_OFFSET 0x00000340
#define IOMUXC_I2C1_IPP_SCL_IND_SELECT_INPUT_OFFSET 0x00000344
#define IOMUXC_I2C1_IPP_SDA_IND_SELECT_INPUT_OFFSET 0x00000348
#define IOMUXC_I2C2_IPP_SCL_IND_SELECT_INPUT_OFFSET 0x0000034C
#define IOMUXC_I2C2_IPP_SDA_IND_SELECT_INPUT_OFFSET 0x00000350
#define IOMUXC_MLB_TOP_MLBCLK_IN_SELECT_INPUT_OFFSET 0x00000354
#define IOMUXC_MLB_TOP_MLBDAT_IN_SELECT_INPUT_OFFSET 0x00000358
#define IOMUXC_MLB_TOP_MLBSIG_IN_SELECT_INPUT_OFFSET 0x0000035C
#define IOMUXC_SAI1_IPP_IND_SAI_TXSYNC_SELECT_INPUT_OFFSET 0x00000360
#define IOMUXC_SAI2_IPP_IND_SAI_RXBCLK_SELECT_INPUT_OFFSET 0x00000364
#define IOMUXC_SAI2_IPP_IND_SAI_RXDATA_0_SELECT_INPUT_OFFSET 0x00000368
#define IOMUXC_SAI2_IPP_IND_SAI_RXSYNC_SELECT_INPUT_OFFSET 0x0000036C
#define IOMUXC_SAI2_IPP_IND_SAI_TXBCLK_SELECT_INPUT_OFFSET 0x00000370
#define IOMUXC_SAI2_IPP_IND_SAI_TXSYNC_SELECT_INPUT_OFFSET 0x00000374
#define IOMUXC_SCI_FLX1_IPP_IND_CTS_B_SELECT_INPUT_OFFSET 0x00000378
#define IOMUXC_SCI_FLX1_IPP_IND_SCI_RX_SELECT_INPUT_OFFSET 0x0000037C
#define IOMUXC_SCI_FLX1_IPP_IND_SCI_TX_SELECT_INPUT_OFFSET 0x00000380
#define IOMUXC_SCI_FLX2_IPP_IND_CTS_B_SELECT_INPUT_OFFSET 0x00000384
#define IOMUXC_SCI_FLX2_IPP_IND_SCI_RX_SELECT_INPUT_OFFSET 0x00000388
#define IOMUXC_SCI_FLX2_IPP_IND_SCI_TX_SELECT_INPUT_OFFSET 0x0000038C
#define IOMUXC_SCI_FLX3_IPP_IND_SCI_RX_SELECT_INPUT_OFFSET 0x00000390
#define IOMUXC_SCI_FLX3_IPP_IND_SCI_TX_SELECT_INPUT_OFFSET 0x00000394
#define IOMUXC_SRC_IPP_BOOT_CFG_18_SELECT_INPUT_OFFSET 0x00000398
#define IOMUXC_SRC_IPP_BOOT_CFG_19_SELECT_INPUT_OFFSET 0x0000039C
#define IOMUXC_SRC_IPP_BOOT_CFG_20_SELECT_INPUT_OFFSET 0x000003A0
#define IOMUXC_VIDEO_IN0_IPP_IND_DE_SELECT_INPUT_OFFSET 0x000003A4
#define IOMUXC_VIDEO_IN0_IPP_IND_FID_SELECT_INPUT_OFFSET 0x000003A8
#define IOMUXC_VIDEO_IN0_IPP_IND_PIX_CLK_SELECT_INPUT_OFFSET 0x000003AC

/* IOMUXC Register per module */
#define IOMUXC_SW_MUX_CTL_PAD_PAD_0    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_0_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_1    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_1_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_2    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_2_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_3    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_3_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_4    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_4_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_5    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_5_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_6    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_6_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_7    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_7_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_8    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_8_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_9    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_9_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_10    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_10_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_11    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_11_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_12    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_12_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_13    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_13_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_14    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_14_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_15    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_15_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_16    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_16_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_17    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_17_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_18    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_18_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_19    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_19_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_20    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_20_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_21    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_21_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_22    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_22_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_23    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_23_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_24    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_24_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_25    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_25_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_26    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_26_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_27    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_27_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_28    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_28_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_29    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_29_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_30    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_30_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_31    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_31_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_32    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_32_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_33    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_33_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_34    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_34_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_35    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_35_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_36    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_36_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_37    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_37_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_38    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_38_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_39    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_39_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_40    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_40_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_41    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_41_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_42    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_42_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_43    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_43_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_44    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_44_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_45    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_45_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_46    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_46_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_47    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_47_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_48    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_48_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_49    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_49_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_50    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_50_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_51    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_51_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_52    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_52_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_53    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_53_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_54    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_54_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_55    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_55_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_56    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_56_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_57    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_57_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_58    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_58_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_59    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_59_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_60    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_60_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_61    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_61_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_62    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_62_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_63    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_63_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_64    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_64_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_65    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_65_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_66    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_66_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_67    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_67_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_68    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_68_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_69    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_69_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_70    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_70_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_71    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_71_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_72    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_72_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_73    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_73_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_74    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_74_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_75    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_75_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_76    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_76_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_77    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_77_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_78    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_78_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_79    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_79_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_80    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_80_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_81    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_81_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_82    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_82_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_83    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_83_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_84    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_84_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_85    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_85_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_86    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_86_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_87    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_87_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_88    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_88_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_89    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_89_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_90    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_90_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_91    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_91_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_92    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_92_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_93    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_93_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_94    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_94_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_95    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_95_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_96    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_96_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_97    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_97_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_98    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_98_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_99    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_99_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_100    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_100_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_101    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_101_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_102    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_102_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_103    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_103_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_104    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_104_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_105    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_105_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_106    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_106_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_107    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_107_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_108    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_108_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_109    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_109_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_110    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_110_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_111    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_111_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_112    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_112_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_113    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_113_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_114    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_114_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_115    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_115_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_116    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_116_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_117    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_117_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_118    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_118_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_119    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_119_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_120    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_120_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_121    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_121_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_122    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_122_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_123    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_123_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_124    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_124_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_125    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_125_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_126    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_126_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_127    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_127_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_128    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_128_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_129    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_129_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_130    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_130_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_131    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_131_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_132    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_132_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_133    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_133_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_134    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_PAD_134_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_DDR_RESETB    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_DDR_RESETB_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_DDR_A_15    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_DDR_A_15_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_DDR_A_14    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_DDR_A_14_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_DDR_A_13    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_DDR_A_13_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_DDR_A_12    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_DDR_A_12_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_DDR_A_11    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_DDR_A_11_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_DDR_A_10    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_DDR_A_10_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_DDR_A_9    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_DDR_A_9_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_DDR_A_8    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_DDR_A_8_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_DDR_A_7    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_DDR_A_7_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_DDR_A_6    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_DDR_A_6_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_DDR_A_5    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_DDR_A_5_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_DDR_A_4    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_DDR_A_4_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_DDR_A_3    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_DDR_A_3_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_DDR_A_2    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_DDR_A_2_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_DDR_A_1    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_DDR_A_1_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_DDR_A_0    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_DDR_A_0_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_DDR_BA_2    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_DDR_BA_2_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_DDR_BA_1    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_DDR_BA_1_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_DDR_BA_0    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_DDR_BA_0_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_DDR_CAS_B    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_DDR_CAS_B_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_DDR_CKE_0    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_DDR_CKE_0_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_DDR_CLK_0    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_DDR_CLK_0_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_DDR_CS_B_0    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_DDR_CS_B_0_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_DDR_D_15    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_DDR_D_15_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_DDR_D_14    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_DDR_D_14_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_DDR_D_13    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_DDR_D_13_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_DDR_D_12    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_DDR_D_12_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_DDR_D_11    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_DDR_D_11_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_DDR_D_10    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_DDR_D_10_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_DDR_D_9    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_DDR_D_9_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_DDR_D_8    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_DDR_D_8_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_DDR_D_7    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_DDR_D_7_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_DDR_D_6    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_DDR_D_6_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_DDR_D_5    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_DDR_D_5_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_DDR_D_4    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_DDR_D_4_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_DDR_D_3    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_DDR_D_3_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_DDR_D_2    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_DDR_D_2_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_DDR_D_1    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_DDR_D_1_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_DDR_D_0    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_DDR_D_0_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_DDR_DQM_1    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_DDR_DQM_1_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_DDR_DQM_0    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_DDR_DQM_0_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_DDR_DQS_1    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_DDR_DQS_1_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_DDR_DQS_0    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_DDR_DQS_0_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_DDR_RAS_B    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_DDR_RAS_B_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_DDR_WE_B    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_DDR_WE_B_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_DDR_ODT_0    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_DDR_ODT_0_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_DDR_ODT_1    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_DDR_ODT_1_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_DUMMY_DDRBYTE1    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_DUMMY_DDRBYTE1_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_DUMMY_DDRBYTE2    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_DUMMY_DDRBYTE2_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_DUMMY_SDHCE1    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_DUMMY_SDHCE1_OFFSET)
#define IOMUXC_SW_MUX_CTL_PAD_DUMMY_SDHC2    (IOMUXC_BASE + IOMUXC_SW_MUX_CTL_PAD_DUMMY_SDHC2_OFFSET)
#define IOMUXC_CCM_AUD_EXT_CLK_SELECT_INPUT    (IOMUXC_BASE + IOMUXC_CCM_AUD_EXT_CLK_SELECT_INPUT_OFFSET)
#define IOMUXC_CCM_ENET_EXT_CLK_SELECT_INPUT    (IOMUXC_BASE + IOMUXC_CCM_ENET_EXT_CLK_SELECT_INPUT_OFFSET)
#define IOMUXC_CCM_ENET_TS_CLK_SELECT_INPUT    (IOMUXC_BASE + IOMUXC_CCM_ENET_TS_CLK_SELECT_INPUT_OFFSET)
#define IOMUXC_DSPI1_IPP_IND_SCK_SELECT_INPUT    (IOMUXC_BASE + IOMUXC_DSPI1_IPP_IND_SCK_SELECT_INPUT_OFFSET)
#define IOMUXC_DSPI1_IPP_IND_SIN_SELECT_INPUT    (IOMUXC_BASE + IOMUXC_DSPI1_IPP_IND_SIN_SELECT_INPUT_OFFSET)
#define IOMUXC_DSPI1_IPP_IND_SS_B_SELECT_INPUT    (IOMUXC_BASE + IOMUXC_DSPI1_IPP_IND_SS_B_SELECT_INPUT_OFFSET)
#define IOMUXC_ENET_SWIAHB_IPP_IND_MAC0_TIMER_0_SELECT_INPUT    (IOMUXC_BASE + IOMUXC_ENET_SWIAHB_IPP_IND_MAC0_TIMER_0_SELECT_INPUT_OFFSET)
#define IOMUXC_ENET_SWIAHB_IPP_IND_MAC0_TIMER_1_SELECT_INPUT    (IOMUXC_BASE + IOMUXC_ENET_SWIAHB_IPP_IND_MAC0_TIMER_1_SELECT_INPUT_OFFSET)
#define IOMUXC_ESAI_IPP_IND_FST_SELECT_INPUT    (IOMUXC_BASE + IOMUXC_ESAI_IPP_IND_FST_SELECT_INPUT_OFFSET)
#define IOMUXC_ESAI_IPP_IND_SCKT_SELECT_INPUT    (IOMUXC_BASE + IOMUXC_ESAI_IPP_IND_SCKT_SELECT_INPUT_OFFSET)
#define IOMUXC_ESAI_IPP_IND_SDO0_SELECT_INPUT    (IOMUXC_BASE + IOMUXC_ESAI_IPP_IND_SDO0_SELECT_INPUT_OFFSET)
#define IOMUXC_ESAI_IPP_IND_SDO1_SELECT_INPUT    (IOMUXC_BASE + IOMUXC_ESAI_IPP_IND_SDO1_SELECT_INPUT_OFFSET)
#define IOMUXC_ESAI_IPP_IND_SDO2_SDI3_SELECT_INPUT    (IOMUXC_BASE + IOMUXC_ESAI_IPP_IND_SDO2_SDI3_SELECT_INPUT_OFFSET)
#define IOMUXC_ESAI_IPP_IND_SDO3_SDI2_SELECT_INPUT    (IOMUXC_BASE + IOMUXC_ESAI_IPP_IND_SDO3_SDI2_SELECT_INPUT_OFFSET)
#define IOMUXC_ESAI_IPP_IND_SDO4_SDI1_SELECT_INPUT    (IOMUXC_BASE + IOMUXC_ESAI_IPP_IND_SDO4_SDI1_SELECT_INPUT_OFFSET)
#define IOMUXC_ESAI_IPP_IND_SDO5_SDI0_SELECT_INPUT    (IOMUXC_BASE + IOMUXC_ESAI_IPP_IND_SDO5_SDI0_SELECT_INPUT_OFFSET)
#define IOMUXC_FLEXTIMER1_IPP_IND_FTM_CH_0_SELECT_INPUT    (IOMUXC_BASE + IOMUXC_FLEXTIMER1_IPP_IND_FTM_CH_0_SELECT_INPUT_OFFSET)
#define IOMUXC_FLEXTIMER1_IPP_IND_FTM_CH_1_SELECT_INPUT    (IOMUXC_BASE + IOMUXC_FLEXTIMER1_IPP_IND_FTM_CH_1_SELECT_INPUT_OFFSET)
#define IOMUXC_FLEXTIMER1_IPP_IND_FTM_PHA_SELECT_INPUT    (IOMUXC_BASE + IOMUXC_FLEXTIMER1_IPP_IND_FTM_PHA_SELECT_INPUT_OFFSET)
#define IOMUXC_FLEXTIMER1_IPP_IND_FTM_PHB_SELECT_INPUT    (IOMUXC_BASE + IOMUXC_FLEXTIMER1_IPP_IND_FTM_PHB_SELECT_INPUT_OFFSET)
#define IOMUXC_I2C0_IPP_SCL_IND_SELECT_INPUT    (IOMUXC_BASE + IOMUXC_I2C0_IPP_SCL_IND_SELECT_INPUT_OFFSET)
#define IOMUXC_I2C0_IPP_SDA_IND_SELECT_INPUT    (IOMUXC_BASE + IOMUXC_I2C0_IPP_SDA_IND_SELECT_INPUT_OFFSET)
#define IOMUXC_I2C1_IPP_SCL_IND_SELECT_INPUT    (IOMUXC_BASE + IOMUXC_I2C1_IPP_SCL_IND_SELECT_INPUT_OFFSET)
#define IOMUXC_I2C1_IPP_SDA_IND_SELECT_INPUT    (IOMUXC_BASE + IOMUXC_I2C1_IPP_SDA_IND_SELECT_INPUT_OFFSET)
#define IOMUXC_I2C2_IPP_SCL_IND_SELECT_INPUT    (IOMUXC_BASE + IOMUXC_I2C2_IPP_SCL_IND_SELECT_INPUT_OFFSET)
#define IOMUXC_I2C2_IPP_SDA_IND_SELECT_INPUT    (IOMUXC_BASE + IOMUXC_I2C2_IPP_SDA_IND_SELECT_INPUT_OFFSET)
#define IOMUXC_MLB_TOP_MLBCLK_IN_SELECT_INPUT    (IOMUXC_BASE + IOMUXC_MLB_TOP_MLBCLK_IN_SELECT_INPUT_OFFSET)
#define IOMUXC_MLB_TOP_MLBDAT_IN_SELECT_INPUT    (IOMUXC_BASE + IOMUXC_MLB_TOP_MLBDAT_IN_SELECT_INPUT_OFFSET)
#define IOMUXC_MLB_TOP_MLBSIG_IN_SELECT_INPUT    (IOMUXC_BASE + IOMUXC_MLB_TOP_MLBSIG_IN_SELECT_INPUT_OFFSET)
#define IOMUXC_SAI1_IPP_IND_SAI_TXSYNC_SELECT_INPUT    (IOMUXC_BASE + IOMUXC_SAI1_IPP_IND_SAI_TXSYNC_SELECT_INPUT_OFFSET)
#define IOMUXC_SAI2_IPP_IND_SAI_RXBCLK_SELECT_INPUT    (IOMUXC_BASE + IOMUXC_SAI2_IPP_IND_SAI_RXBCLK_SELECT_INPUT_OFFSET)
#define IOMUXC_SAI2_IPP_IND_SAI_RXDATA_0_SELECT_INPUT    (IOMUXC_BASE + IOMUXC_SAI2_IPP_IND_SAI_RXDATA_0_SELECT_INPUT_OFFSET)
#define IOMUXC_SAI2_IPP_IND_SAI_RXSYNC_SELECT_INPUT    (IOMUXC_BASE + IOMUXC_SAI2_IPP_IND_SAI_RXSYNC_SELECT_INPUT_OFFSET)
#define IOMUXC_SAI2_IPP_IND_SAI_TXBCLK_SELECT_INPUT    (IOMUXC_BASE + IOMUXC_SAI2_IPP_IND_SAI_TXBCLK_SELECT_INPUT_OFFSET)
#define IOMUXC_SAI2_IPP_IND_SAI_TXSYNC_SELECT_INPUT    (IOMUXC_BASE + IOMUXC_SAI2_IPP_IND_SAI_TXSYNC_SELECT_INPUT_OFFSET)
#define IOMUXC_SCI_FLX1_IPP_IND_CTS_B_SELECT_INPUT    (IOMUXC_BASE + IOMUXC_SCI_FLX1_IPP_IND_CTS_B_SELECT_INPUT_OFFSET)
#define IOMUXC_SCI_FLX1_IPP_IND_SCI_RX_SELECT_INPUT    (IOMUXC_BASE + IOMUXC_SCI_FLX1_IPP_IND_SCI_RX_SELECT_INPUT_OFFSET)
#define IOMUXC_SCI_FLX1_IPP_IND_SCI_TX_SELECT_INPUT    (IOMUXC_BASE + IOMUXC_SCI_FLX1_IPP_IND_SCI_TX_SELECT_INPUT_OFFSET)
#define IOMUXC_SCI_FLX2_IPP_IND_CTS_B_SELECT_INPUT    (IOMUXC_BASE + IOMUXC_SCI_FLX2_IPP_IND_CTS_B_SELECT_INPUT_OFFSET)
#define IOMUXC_SCI_FLX2_IPP_IND_SCI_RX_SELECT_INPUT    (IOMUXC_BASE + IOMUXC_SCI_FLX2_IPP_IND_SCI_RX_SELECT_INPUT_OFFSET)
#define IOMUXC_SCI_FLX2_IPP_IND_SCI_TX_SELECT_INPUT    (IOMUXC_BASE + IOMUXC_SCI_FLX2_IPP_IND_SCI_TX_SELECT_INPUT_OFFSET)
#define IOMUXC_SCI_FLX3_IPP_IND_SCI_RX_SELECT_INPUT    (IOMUXC_BASE + IOMUXC_SCI_FLX3_IPP_IND_SCI_RX_SELECT_INPUT_OFFSET)
#define IOMUXC_SCI_FLX3_IPP_IND_SCI_TX_SELECT_INPUT    (IOMUXC_BASE + IOMUXC_SCI_FLX3_IPP_IND_SCI_TX_SELECT_INPUT_OFFSET)
#define IOMUXC_SRC_IPP_BOOT_CFG_18_SELECT_INPUT    (IOMUXC_BASE + IOMUXC_SRC_IPP_BOOT_CFG_18_SELECT_INPUT_OFFSET)
#define IOMUXC_SRC_IPP_BOOT_CFG_19_SELECT_INPUT    (IOMUXC_BASE + IOMUXC_SRC_IPP_BOOT_CFG_19_SELECT_INPUT_OFFSET)
#define IOMUXC_SRC_IPP_BOOT_CFG_20_SELECT_INPUT    (IOMUXC_BASE + IOMUXC_SRC_IPP_BOOT_CFG_20_SELECT_INPUT_OFFSET)
#define IOMUXC_VIDEO_IN0_IPP_IND_DE_SELECT_INPUT    (IOMUXC_BASE + IOMUXC_VIDEO_IN0_IPP_IND_DE_SELECT_INPUT_OFFSET)
#define IOMUXC_VIDEO_IN0_IPP_IND_FID_SELECT_INPUT    (IOMUXC_BASE + IOMUXC_VIDEO_IN0_IPP_IND_FID_SELECT_INPUT_OFFSET)
#define IOMUXC_VIDEO_IN0_IPP_IND_PIX_CLK_SELECT_INPUT    (IOMUXC_BASE + IOMUXC_VIDEO_IN0_IPP_IND_PIX_CLK_SELECT_INPUT_OFFSET)



/* Field definitions for IOMUXC_SW_MUX_CTL_PAD_PAD_n */
#define IOMUXC_SW_MUX_CTL_PAD_PAD_n_MUX_MODE_SHIFT          (20)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_n_MUX_MODE_MASK           ((0x00000007) <<(IOMUXC_SW_MUX_CTL_PAD_PAD_n_MUX_MODE_SHIFT)) 

#define IOMUXC_SW_MUX_CTL_PAD_PAD_n_SPEED_SHIFT             (12)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_n_SPEED_MASK              ((0x00000003) <<(IOMUXC_SW_MUX_CTL_PAD_PAD_n_SPEED_SHIFT)) 

#define IOMUXC_SW_MUX_CTL_PAD_PAD_n_SRE_SHIFT               (11)  
#define IOMUXC_SW_MUX_CTL_PAD_PAD_n_SRE_MASK                ((1) <<(IOMUXC_SW_MUX_CTL_PAD_PAD_n_SRE_SHIFT)) 

#define IOMUXC_SW_MUX_CTL_PAD_PAD_n_ODE_SHIFT               (10)  
#define IOMUXC_SW_MUX_CTL_PAD_PAD_n_ODE_MASK                ((1) <<(IOMUXC_SW_MUX_CTL_PAD_PAD_n_ODE_SHIFT)) 

#define IOMUXC_SW_MUX_CTL_PAD_PAD_n_HYS_SHIFT               (9)  
#define IOMUXC_SW_MUX_CTL_PAD_PAD_n_HYS_MASK                ((1) <<(IOMUXC_SW_MUX_CTL_PAD_PAD_n_HYS_SHIFT)) 

#define IOMUXC_SW_MUX_CTL_PAD_PAD_n_DSE_SHIFT               (6)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_n_DSE_MASK                ((0x00000007) <<(IOMUXC_SW_MUX_CTL_PAD_PAD_n_DSE_SHIFT)) 

#define IOMUXC_SW_MUX_CTL_PAD_PAD_n_PUS_SHIFT               (4)
#define IOMUXC_SW_MUX_CTL_PAD_PAD_n_PUS_MASK                ((0x00000003) <<(IOMUXC_SW_MUX_CTL_PAD_PAD_n_PUS_SHIFT)) 

#define IOMUXC_SW_MUX_CTL_PAD_PAD_n_PKE_SHIFT               (3)  
#define IOMUXC_SW_MUX_CTL_PAD_PAD_n_PKE_MASK                ((1) <<(IOMUXC_SW_MUX_CTL_PAD_PAD_n_PKE_SHIFT)) 

#define IOMUXC_SW_MUX_CTL_PAD_PAD_n_PUE_SHIFT               (2)  
#define IOMUXC_SW_MUX_CTL_PAD_PAD_n_PUE_MASK                ((1) <<(IOMUXC_SW_MUX_CTL_PAD_PAD_n_PUE_SHIFT)) 

#define IOMUXC_SW_MUX_CTL_PAD_PAD_n_OBE_SHIFT               (1)  
#define IOMUXC_SW_MUX_CTL_PAD_PAD_n_OBE_MASK                ((1) <<(IOMUXC_SW_MUX_CTL_PAD_PAD_n_OBE_SHIFT)) 

#define IOMUXC_SW_MUX_CTL_PAD_PAD_n_IBE_SHIFT               (0)  
#define IOMUXC_SW_MUX_CTL_PAD_PAD_n_IBE_MASK                ((1) <<(IOMUXC_SW_MUX_CTL_PAD_PAD_n_IBE_SHIFT)) 



/* Field definitions for IOMUXC_SW_MUX_CTL_PAD_DDR_n */
#define IOMUXC_SW_MUX_CTL_PAD_DDR_n_DDR_INPUT_SHIFT         (16)  
#define IOMUXC_SW_MUX_CTL_PAD_DDR_n_DDR_INPUT_MASK          ((1) << (IOMUXC_SW_MUX_CTL_PAD_DDR_n_DDR_INPUT_SHIFT)) 

#define IOMUXC_SW_MUX_CTL_PAD_DDR_n_DDR_TRIM_SHIFT          (14)
#define IOMUXC_SW_MUX_CTL_PAD_DDR_n_DDR_TRIM_MASK           ((0x00000003) << (IOMUXC_SW_MUX_CTL_PAD_DDR_n_DDR_TRIM_SHIFT)) 

#define IOMUXC_SW_MUX_CTL_PAD_DDR_n_HYS_SHIFT               (9)  
#define IOMUXC_SW_MUX_CTL_PAD_DDR_n_HYS_MASK                ((1) <<(IOMUXC_SW_MUX_CTL_PAD_DDR_n_HYS_SHIFT)) 

#define IOMUXC_SW_MUX_CTL_PAD_DDR_n_DSE_SHIFT               (6)
#define IOMUXC_SW_MUX_CTL_PAD_DDR_n_DSE_MASK                ((0x00000007) <<(IOMUXC_SW_MUX_CTL_PAD_DDR_n_DSE_SHIFT)) 

#define IOMUXC_SW_MUX_CTL_PAD_DDR_n_PUS_SHIFT               (4)
#define IOMUXC_SW_MUX_CTL_PAD_DDR_n_PUS_MASK                ((0x00000003) <<(IOMUXC_SW_MUX_CTL_PAD_DDR_n_PUS_SHIFT)) 

#define IOMUXC_SW_MUX_CTL_PAD_DDR_n_PKE_SHIFT               (3)  
#define IOMUXC_SW_MUX_CTL_PAD_DDR_n_PKE_MASK                ((1) <<(IOMUXC_SW_MUX_CTL_PAD_DDR_n_PKE_SHIFT)) 

#define IOMUXC_SW_MUX_CTL_PAD_DDR_n_PUE_SHIFT               (2)  
#define IOMUXC_SW_MUX_CTL_PAD_DDR_n_PUE_MASK                ((1) <<(IOMUXC_SW_MUX_CTL_PAD_DDR_n_PUE_SHIFT)) 



/* Field definitions for IOMUXC_n */
#define IOMUXC_n_DAISY_SHIFT         (0)  
#define IOMUXC_n_DAISY_MASK          ((0x00000003) << (IOMUXC_n_DAISY_SHIFT)) 


/*** End of bit definitions ***/

/*** define base address ***/
#define IOMUXC_BASE 	0x40048000

#endif //_IOMUX_DEFINES_H_
